config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users, only: [:show, :edit, :update]


get "joke_found" => "static#joke_found"
root "static#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	
def index
# response = Unirest.get('https://api.chucknorris.io/jokes/random')
# # byebug
# @joke = response.body['value']

# These code snippets use an open-source library.
response = Unirest.get "https://musixmatchcom-musixmatch.p.mashape.com/wsr/1.1/artist.get?artist_id=1000",
  headers:{
    "X-Mashape-Key" => "vxGXmAkKjomshOtw6d3nysdrKzK1p1ntw02jsna6xI8aEt5SfE",
    "Accept" => "application/json"
  }
  byebug
 end

def joke_found
response = Unirest.get("https://api.chucknorris.io/jokes/search?query=#{params[:query]}")
# byebug
total_jokes = response.body["total"]
if total_jokes != nil
	@jokenew = response.body["result"][0]["value"]
	@icon_url = response.body["result"][0]["icon_url"]
else
	response = Unirest.get('http://api.icndb.com/jokes/random')
# byebug
	@joke = response.body["value"]["joke"]
	@icon_url = ""  
	end
end


end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
#ApplicationController
def show
@user = User.find_by_id(params[:id])
 end


def edit
@user = User.find(params[:id])
	end

	def update
		@user = User.find(current_user)
		@user.update(user_params)
		redirect_to root_path
		flash[:notice]= "Done Homie"

	end


private


def user_params

params.require(:user).permit(:email)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= link_to 'Home', root_path %>
   <% if current_user %>
        <%= link_to 'Profile', user_path(current_user)%>
        <%= link_to 'Have a Joke', joke_found_path %>

    <% end %>
<!-- button_to -->
  <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= link_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

   

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2>Edit User</h2>

	<%= form_for @user do |form|%>
	<%= form.label :email%>
	<%= form.text_field :email %>
<%= form.submit%>
	<% end %>

app/views/users/show.html.erb
<h2>My Profile </h2>

<% if current_user == @user%>
	Email: <%= @user.email %>
 

 <%= link_to 'Edit Profile', edit_user_path(current_user) %>
	<% end %>
 